version: '3.4'

services:
  quizyzuna-db:
    container_name: Database
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=quizyzuna-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgressql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  quizyzuna-api:
    container_name: API
    image: ${DOCKER_REGISTRY-}quizyzunaapi
    build:
      context: src/
    depends_on:
        quizyzuna-db:
          condition: service_healthy
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=Database;Username=postgres;Password=postgres;Database=quizyzuna-db;
    ports:
      - "5215:5215"