version: '3.4'

services:
  quizyzunaapi-db:
    container_name: Database
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=quizyzuna-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.containers/database:/var/lib/postgressql/data

  quizyzunaapi.api:
    container_name: API
    image: ${DOCKER_REGISTRY-}quizyzunaapi
    build:
      context: .
      dockerfile: src/QuizyZunaAPI.Api/Dockerfile