# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore ./QuizyZunaAPI.sln
    - name: Build
      run: dotnet build ./QuizyZunaAPI.sln --no-restore
    - name: Test
      run: dotnet test ./QuizyZunaAPI.sln --no-build --verbosity normal
